language: node_js
sudo: false
node_js: '6'
cache:
  directories:
  - node_modules
before_install:
- npm install -g grunt-cli
install:
- npm install
script:
- grunt gh-deploy-travis
env:
  global:
    secure: wCH50zZlZ9nasZlJsuBQ7ob8jGsXvGzryHdCxwsCslYI8pBYKaQmwRqspMzNdtGnkOiHbbC0FabkeR20/jubSwsn2Q5GkiEdkREm8uSbyYVqjJ5w1quxrwCKm58OWLp8ndvIMAsBKwFco9az7Aio9cgHGwBR9sKGiyMQd5qi5DmzO4zlunkPGLX5wO+vMrKEfWJY2YVTZTnkjyFFmEmaRgwnpniyYE0JZF5XU6rgAHi5yAUgHrnYffZl9ANrFiNuL3Q0DMtSpASOjhzrYcHRdUDgpKdJuDlZ1Ru1GBOjoJs2+IAmxLsWgJjdG4MlcxYYajD+Z8xOPxrsZ7F9QK6rrvOkENFobvcOD7qio/8W5Wtd6JCSG0b7XHVhk+3LTtFpfovi5sZy6e315m4bqIxIEFA8Gne9+HCASiHN6V2SpC8zBTcxRr2Y7VLGt9QXyj53zJTZNtJd3jOs65SFzb6oEOVxD4YmqS5pplIjLAAUS7t9oVaZMhQ1DD7y3+BaECP5XThccQ/zmmUfNiPR+kq2MreYjiRX/5gfMdFNGgY7Jw89DkSOg7EHynNeXjYXodft6/zaLHpJ+kDloMSUHKFhzAnDNuIUJ0ZQo2yAokHFJVFEE1/bheh/UKgNtMTdJbHPuxZxtDk6Y3AqozCszitaUskSk4d6xmDtvK1SBsKQvmg=
